---
title: "Lec04"
output: pdf_document
---

```{r}
#| message: false
library(tidyverse)
```

```{r}
N = 1000
set.seed(777)
darkness = rnorm(N, 80, 5)
darkness = ifelse(darkness >= 99, 99, darkness)
```

```{r}
data.frame(darkness) |>
    ggplot(aes(x=darkness)) +
    geom_histogram(binwidth=3) + 
    # geom_vline(xintercept=20, color="red") +
    labs(x = "Sheep Face Darkness (%)",
         y = "# Sheep",
         title = "Normal sheep faces") +
    xlim(0, 100)
ggsave("animal_faces.png")
```

```{r}
set.seed(777)
NBP = 200
BP_MEAN = 100
BP_VAR = 10
bp = rnorm(NBP, BP_MEAN, BP_VAR)
data.frame(bp) |>
    ggplot(aes(x=bp)) +
    geom_histogram(binwidth=5) + 
    # geom_vline(xintercept=20, color="red") +
    labs(x = "Blood Pressure (Diastolic)",
         y = "# People",
         title = "Normal people blood pressure (no drug)") +
    xlim(0, max(bp) + 1)
ggsave("bp_dist.png")
```

```{r}
bp2 = rnorm(NBP, BP_MEAN - 10, BP_VAR)

frame = data.frame(bp = c(bp, bp2), drug=c(rep("no drug", NBP), rep("yes drug", NBP)))
frame |>
    ggplot(aes(x=bp, fill=drug)) +
    geom_histogram(position = "identity", binwidth=5, alpha=0.6) + 
    # geom_vline(xintercept=20, color="red") +
    labs(x = "Blood Pressure (Diastolic)",
         y = "# People",
         title = "Blood pressure with and without new drug") +
    xlim(0, max(bp) + 1)
ggsave("bp_groups.png")
```
