---
title: "Lecture05_CodeAlong"
output: pdf_document
---

```{r}
#| message: false
library(tidyverse)
```

```{r}
class = read_csv('data/class_survey_simplified.csv')
```

```{r}
gimme_barplot = function(colname) {
  class |>
    ggplot(aes_string(x = colname, fill=colname)) +
    geom_bar()
}

gimme_barplot("major")
gimme_barplot("language")
```

```{r}
class |>
  group_by(language) |>
  summarize(mean=mean(comfort_coding))
```

```{r}
r_coders = class |>
  filter(language == "R")
py_coders = class |>
  filter(language == "Python")

r_comfort_mean = mean(r_coders$comfort_coding)
py_comfort_mean = mean(py_coders$comfort_coding)

observed_stat = abs(r_comfort_mean - py_comfort_mean)
observed_stat
```

```{r}
get_test_stat = function(dataset) {
  r_coders = dataset |>
    filter(language == "R")
  py_coders = dataset |>
    filter(language == "Python")
  
  r_comfort_mean = mean(r_coders$comfort_coding)
  py_comfort_mean = mean(py_coders$comfort_coding)
  
  stat = abs(r_comfort_mean - py_comfort_mean)
  return(stat)
}
get_test_stat(class)
```

```{r}
x = c(1,2,3,4)
sample(x)
```

```{r}
simulate_once = function() {
  permuted = class |>
    mutate(language = sample(language))
  return(get_test_stat(permuted))
}
```

```{r}
null_test_statistics = replicate(1000, simulate_once())
```

```{r}
observed_stat = get_test_stat(class)

p = mean(null_test_statistics > observed_stat)

data.frame(stat = null_test_statistics) |>
  ggplot(aes(x=stat)) +
  geom_histogram(binwidth=0.25) +
  geom_vline(xintercept=observed_stat, color="red") +
  annotate("label", observed_stat, 0, label=p)
```
